---
language: node_js
node_js:
  - 'stable'
env:
  secure: djYzdIuDh/Mv+CuoMk/jm3+7VbZL51GnrDzQAA7WIhv9c+/3MpdzoIy8D9sKZsDtZGViJQASiVpKzRSpMmCxlq8fxZAkRBBh69WHwW15HCZnPSPmmOIgWM9bemHlNTIHC0R/vyTAJdVGy7JitqZDdBluwx5Fr5pZWdOrNjq+5+Vj42abCwR739SCliOos81GBDqYiBOfFKlCgH7uebqiG7a87r0rgB3AW3Q/Q4GG6zKZJHaFfvS7a+KzKb1ymEJWYM7DmzU6kxEgvocjerHU/zlh1ZK3ljgSXGhrw+8h7JKksQj/HtrWv7tcZbPZ4a03F1PM7bug8NfvdFzYMR8FCl8niDLq7vW+3h1NqRuuQ1XovqHbEI+MctROenUj6ZXU3wPYxORXhSQ1MF9utBS/I9yS4KdWjMdP17KTwXejYSK9QlSRaheT4RDjXwS2HBr/R/rSXFUt54l0zEuSdq/AOIBzdEg8BmyNLJTr23aYPtVv1uXitRKtcV27G1+mZezZvVEngLYilUguHNZxp39Tm+l4m9YM+Z9mBFjYEgyPeXLgoOr/Cu6HToKuKLFw/2waItBBtjuqiKGU2zrv8pn4CfBD/U2axsfVkEaK8UuuA2CWVRqgl/O49yoHtsE0BJpO90YEi8/jmjBaOpHYu09pU35NwWguqR+AVpzUIkHusqg=
cache: yarn
script:
  - yarn lint
  - yarn test
  - yarn generate
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
notifications:
  email: false
  slack:
    secure: TsFSirdMP4dW5gJh7Fi05xDXt1PJ5dKh49U6J1bShSSMGyTuYxVpj8vWX2obmmYhiEnc8gUABqVeIgzRFOpbK9fnyK8D/sKcRruxGFK8U6V0CyvqcVULjN9cwKyvANUtAYd7xoSB4xR9JOoqiryridqFLONyakQIeikK1/yhh1OWgFO1+4OU9sdkOBW69EKmYlDHPcuEMi5MV+e4md6vt7/LxSLgtVYN128y/EZoeJgi/DJ3kBOY4Ley6QP88cIDBmkXO38t6nTVElWK1QdRiAAoa4CQ4GrG6NcTP5qtLV3WN1WQqbWSxbjJw13Wba4Oj4RmLoQc7F2lRLsnh80/FsJXLKEvTJzgfIx8q8k/hR/t3ZlzMcOPpLt+cgs7F2+Ipfot9T3IhS8hG7cxKbmI15jFv6HCirZbvxbPcewOujdxeyItVE3v93cbP6/ye521Mo1WdREVetqWyjKQA/NWq3OH1DOoruEyIZ4LMkHDHYTp2n73BFCqvr7zKwcQsLm67BXfggtg9Y5YuQQsTltRM58PVxsm1RHtdO8CM1FalGyXi2LorBpsfDX8G394dQoPXlHlGSi08ikkO2n+/TdjIEubQJEJ7j3RHKTehbwyCWVshBT3B3TKnJUyGjGdciV4LOxbdsxK9+FhCxR8HX/mVvlFwE1+Za92hPdrzMBU7+s=
